project:
  type: website
  output-dir: docs

website:
  title: "Curso Precongreso"
  navbar:
    left:
      - href: index.qmd
        text: Inicio

format:
  html:
    theme: journal
    css: styles.css
    toc: true



