project:
  type: website
  output-dir: docs

website:
  title: "Curso Precongreso"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: IAR_doc.qmd
        text: Script IAR
      - href: Diversidad Congreso.qmd
        text: Script Diversidad
        

format:
  html:
    theme: journal
    css: styles.css
    toc: true



